language: python

python:
  - "3.4"

services: mysql

env:
  global:
    - DJANGO_SETTINGS_MODULE="my_site.settings"
    - PYTHONPATH="/home/travis/build/my_github_name/my_github_project"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO=1.7 DB=mysql

install:
  - pip install -q Django==$DJANGO

before_script:
  - mysql -e 'create database travis_ci_db;'

#command to run the test suite
script:
  - python manage.py test
